-- Clinic field expansion to match the frontend contract.

ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'THERAPIST';
ALTER TYPE "ServiceCategory" ADD VALUE IF NOT EXISTS 'TRICHOLOGY';

CREATE TYPE "VisitType" AS ENUM ('CONSULTATION', 'PROCEDURE', 'REVIEW', 'PATCH_TEST', 'FOLLOW_UP');
CREATE TYPE "TreatmentArea" AS ENUM ('SCALP_FRONTAL', 'SCALP_VERTEX', 'SCALP_TEMPORAL', 'SCALP_CROWN', 'SCALP_NAPE', 'FULL_SCALP', 'BEARD', 'EYEBROWS', 'FACE', 'NECK', 'BODY', 'OTHER');
CREATE TYPE "PrepStatus" AS ENUM ('NOT_REQUIRED', 'PENDING', 'COMPLETED');
CREATE TYPE "ReminderChannel" AS ENUM ('WHATSAPP', 'SMS', 'CALL', 'EMAIL', 'NONE');
CREATE TYPE "BookingSource" AS ENUM ('WALK_IN', 'PHONE', 'WHATSAPP', 'INSTAGRAM', 'FOLLOW_UP', 'OTHER');
CREATE TYPE "FitzpatrickType" AS ENUM ('I', 'II', 'III', 'IV', 'V', 'VI');
CREATE TYPE "ScalpType" AS ENUM ('OILY', 'DRY', 'COMBINATION', 'SENSITIVE', 'NORMAL');
CREATE TYPE "HairType" AS ENUM ('STRAIGHT', 'WAVY', 'CURLY', 'COILY');
CREATE TYPE "HairLossScale" AS ENUM ('NORWOOD', 'LUDWIG', 'SINCLAIR');
CREATE TYPE "InterestCategory" AS ENUM ('SKIN', 'HAIR', 'TRICHOLOGY', 'WELLNESS');
CREATE TYPE "LeadLostReason" AS ENUM ('PRICE', 'CHOSE_ANOTHER_CLINIC', 'NOT_READY', 'UNREACHABLE', 'OTHER');

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "registrationNumber" TEXT,
ADD COLUMN IF NOT EXISTS "calendarColor" TEXT,
ADD COLUMN IF NOT EXISTS "workingHours" TEXT,
ADD COLUMN IF NOT EXISTS "commissionPercent" DOUBLE PRECISION;

ALTER TABLE "Patient"
ADD COLUMN IF NOT EXISTS "mrn" TEXT,
ADD COLUMN IF NOT EXISTS "whatsapp" TEXT,
ADD COLUMN IF NOT EXISTS "reminderChannel" "ReminderChannel",
ADD COLUMN IF NOT EXISTS "emergencyContactName" TEXT,
ADD COLUMN IF NOT EXISTS "emergencyContactPhone" TEXT,
ADD COLUMN IF NOT EXISTS "occupation" TEXT,
ADD COLUMN IF NOT EXISTS "lifestyleNotes" TEXT,
ADD COLUMN IF NOT EXISTS "familyHistoryAlopecia" BOOLEAN,
ADD COLUMN IF NOT EXISTS "smokingStatus" TEXT,
ADD COLUMN IF NOT EXISTS "leadId" TEXT,
ADD COLUMN IF NOT EXISTS "billingName" TEXT,
ADD COLUMN IF NOT EXISTS "preferredLanguage" TEXT,
ADD COLUMN IF NOT EXISTS "fitzpatrickType" "FitzpatrickType",
ADD COLUMN IF NOT EXISTS "scalpType" "ScalpType",
ADD COLUMN IF NOT EXISTS "hairType" "HairType",
ADD COLUMN IF NOT EXISTS "hairLossScale" "HairLossScale",
ADD COLUMN IF NOT EXISTS "hairLossGrade" TEXT,
ADD COLUMN IF NOT EXISTS "wellnessConcerns" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "ClinicService"
ADD COLUMN IF NOT EXISTS "bufferMinutes" INTEGER,
ADD COLUMN IF NOT EXISTS "hsnSac" TEXT,
ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "requiresPatchTest" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "requiresConsent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isPackage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "defaultSessionCount" INTEGER;

ALTER TABLE "Appointment"
ADD COLUMN IF NOT EXISTS "visitType" "VisitType" NOT NULL DEFAULT 'CONSULTATION',
ADD COLUMN IF NOT EXISTS "chiefComplaint" TEXT,
ADD COLUMN IF NOT EXISTS "treatmentArea" "TreatmentArea",
ADD COLUMN IF NOT EXISTS "sessionNumber" INTEGER,
ADD COLUMN IF NOT EXISTS "totalSessions" INTEGER,
ADD COLUMN IF NOT EXISTS "consentStatus" "PrepStatus",
ADD COLUMN IF NOT EXISTS "patchTestStatus" "PrepStatus",
ADD COLUMN IF NOT EXISTS "room" TEXT,
ADD COLUMN IF NOT EXISTS "bookingSource" "BookingSource",
ADD COLUMN IF NOT EXISTS "reminderChannel" "ReminderChannel",
ADD COLUMN IF NOT EXISTS "depositExpected" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "treatmentId" TEXT,
ADD COLUMN IF NOT EXISTS "invoiceId" TEXT;

ALTER TABLE "Treatment"
ADD COLUMN IF NOT EXISTS "therapistName" TEXT,
ADD COLUMN IF NOT EXISTS "appointmentId" TEXT,
ADD COLUMN IF NOT EXISTS "treatmentArea" "TreatmentArea",
ADD COLUMN IF NOT EXISTS "parameters" TEXT,
ADD COLUMN IF NOT EXISTS "consumablesUsed" TEXT,
ADD COLUMN IF NOT EXISTS "adverseReaction" TEXT,
ADD COLUMN IF NOT EXISTS "aftercare" TEXT,
ADD COLUMN IF NOT EXISTS "nextSessionDate" TEXT,
ADD COLUMN IF NOT EXISTS "diagnosis" TEXT,
ADD COLUMN IF NOT EXISTS "trichoscopyNotes" TEXT;

ALTER TABLE "Invoice"
ADD COLUMN IF NOT EXISTS "billedToName" TEXT,
ADD COLUMN IF NOT EXISTS "appointmentId" TEXT,
ADD COLUMN IF NOT EXISTS "treatmentId" TEXT,
ADD COLUMN IF NOT EXISTS "cgst" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "sgst" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "roundOff" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "InvoiceItem"
ADD COLUMN IF NOT EXISTS "hsnSac" TEXT,
ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION;

ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "manufacturer" TEXT,
ADD COLUMN IF NOT EXISTS "batchLot" TEXT,
ADD COLUMN IF NOT EXISTS "expiryDate" TEXT,
ADD COLUMN IF NOT EXISTS "storageLocation" TEXT,
ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "retailUse" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "StockMovement"
ADD COLUMN IF NOT EXISTS "treatmentId" TEXT;

ALTER TABLE "Lead"
ADD COLUMN IF NOT EXISTS "whatsapp" TEXT,
ADD COLUMN IF NOT EXISTS "city" TEXT,
ADD COLUMN IF NOT EXISTS "gender" "Gender",
ADD COLUMN IF NOT EXISTS "interestCategory" "InterestCategory",
ADD COLUMN IF NOT EXISTS "lostReason" "LeadLostReason",
ADD COLUMN IF NOT EXISTS "convertedPatientId" TEXT;

ALTER TABLE "Coupon"
ADD COLUMN IF NOT EXISTS "maxUsesPerPatient" INTEGER,
ADD COLUMN IF NOT EXISTS "applicableCategory" "ServiceCategory",
ADD COLUMN IF NOT EXISTS "firstVisitOnly" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "packageOnly" BOOLEAN NOT NULL DEFAULT false;
